### ISSUE TITLE
[Help Needed] Need help in setting up this start page

### ISSUE THREAD

**Issue by ghost** [not-a-dev-stein/firefox-popdark-startpage#1]
Hello , I wanted to setup this as my start page can you please guide me how can i achieve that?

**Comment by not-a-dev-stein** [comment]
I'm not that literate with code, so what I can do to help is to retrace my steps.

What you can do is fork the project for yourself (right on the top of the project page, next to the title), which means you would have a version of the same code to work with.
Then, when you'd go to your version of the project page, you can edit the index.html inside the startpage_alt2 file with your preferred webpages just under:

> "< div class="bookmark-inner-container">

> < a class="bookmark" href="link of your website"> "name of the website"</a>

After having everything suited just for you you have two options: 

- If all you want is to have this as the startpage for when you open Firefox all you have to do is to download the files to anywhere on your PC and link it at Firefox's "home" section at preferences. It will look something like 

> /home/stein/.mozilla/firefox/9clsj630.default-release-1589600489313/starpage_alt2" 
(this is where it is saved on my system, but you can just have it anywhere).

- Or, if you want to use it as the new tab page as well as the startpage, all you have to do is to go to the branch menu (a little under the "commits" area) and create a branch called "gh-pages". With that you host a version of that code as a website on GitHub, and with that you can use it as your startpage with both Firefox's startpage section and with the [New Tab Override](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/) extension to use it as your new tab page as well. It will be hosted under:
> https://(yourusername).github.io/firefox-popdark-startpage/startpage_alt2/index.html

- After that you can just download the extension and paste the link there and on Firefox's home section under preferences.

Let me know if that helped you.

**Comment by ghost** [comment]
Thanks a lot for your guidance that worked for me :heart:
